hackaton_cleaner_job_homepage:
    path:     /jobs
    defaults: { _controller: HackatonCleanerJobBundle:Job:index }

hackaton_cleaner_job_new:
    path:     /jobs/new
    defaults: { _controller: HackatonCleanerJobBundle:Job:new }
hackaton_cleaner_job_view:
    path:     /jobs/{id}/view
    defaults: { _controller: HackatonCleanerJobBundle:Job:view }
hackaton_cleaner_job_edit:
    path:     /jobs/{id}/edit
    defaults: { _controller: HackatonCleanerJobBundle:Job:edit }


hackaton_cleaner_job_apply:
    path:     /applyjobs/{jobId}/new
    defaults: { _controller: HackatonCleanerJobBundle:JobApply:new }
hackaton_cleaner_job_apply_view:
    path:     /applyjobs/{jobId}/view
    defaults: { _controller: HackatonCleanerJobBundle:JobApply:view }
hackaton_cleaner_job_apply_approve:
    path:     /applyjobs/{id}/approve
    defaults: { _controller: HackatonCleanerJobBundle:Job:applicationApprove }
