# Profile
user_manage_profile:
    path:     /profile/manage
    defaults: { _controller: HackatonUserBundle:Profile:manage }

user_show_profile:
    path:     /profile/show/{id}
    defaults: { _controller: HackatonUserBundle:Profile:show , id: 0 }

add_food:
    path:     /add/food
    defaults: { _controller: HackatonUserBundle:Order:addFood }
